%{
%
%   Writen by Petru Cojea on 22.04.2019
%
%}

addpath('cpp_src');
addpath('cpp_src\Extra','cpp_src\INFO','cpp_src\OpenCL_Core','cpp_src\OpenCL_Extra','cpp_src\Power_System_Core','cpp_src\Power_System_Extra');


mex -g ...
    cpp_src\mex_Newton_Raphson_OpenCL.cpp...
    cpp_src\main.cpp...
    cpp_src\Power_System_Core\PSC_nodes.cpp...
    cpp_src\Power_System_Core\PSC_lines.cpp...
    cpp_src\Power_System_Extra\PSE_Power_Flow_Data.cpp...
    cpp_src\OpenCL_Core\OCLC_Compute_Obj.cpp...
    cpp_src\OpenCL_Core\OCLC_Compute_Obj_Extra_01.cpp...
    cpp_src\OpenCL_Core\OCLC_Compute_Obj_Extra_02.cpp...
    -I'D:\Dev\Matlab\Newton_Raphson_OpenCL_MEX\cpp_src'...
    -I'C:\NVIDIA\CUDA\include'...
    -L'C:\NVIDIA\CUDA\lib\x64'...
    -l'OpenCL'

mex_compiled = 1;