#ifndef OPENCL_POWERFLOW_POWER_SYSTEM_ELEMENT_TYPES_H
#define OPENCL_POWERFLOW_POWER_SYSTEM_ELEMENT_TYPES_H

enum class DataTypes{
	VECTOR_1D,
	VECTOR_2D,
	MATLAB_DATA_1D,
	MATLAB_DATA_2D,
	OPENCL_BUFFER_1D,
	OPENCL_BUFFER_2D
};

enum class BUS {
	NUMBER,
	TYPE,
	NOMINAL_VOLTAGE,
	GEN_ACTIVE_POW,
	GEN_REACTIVE_POW,
	CONS_ACTIVE_POW,
	CONS_REACTIVE_POW,
	IMPOSED_VOLTAGE,
	MIN_REACTIVE_POW,
	MAX_REACTIVE_POW,
	IMPOSED_ACTIVE_POW,
	IMPOSED_REACTIVE_POW
};

enum class BRANCH {
	FROM,
	TO,
	NOMINAL_VOLTAGE,
	LINE_lENGTH,
	RESISTANCE_0,
	REACTANCE_0,
	CONDUCTANCE_0,
	SUSCEPTANCE_0,
	NR_OF_CONDUCTORS
};

enum class TRANSFORMER {
	FROM,
	TO,
	RESISTANCE_0,
	REACTANCE_0,
	CONDUCTANCE_0,
	SUSCEPTANCE_0,
	TRAFO_REPORT,
	NR_OF_TRAFO
};

enum class GENERATOR{
	//nothing for now
};



#endif //OPENCL_POWERFLOW_POWER_SYSTEM_ELEMENT_TYPES_Hw
