mex -g ...
    ..\oclpf.cpp...
    ..\Power_System\Power_System_Element.cpp...
    ..\Data_Bank\Data_Bank.cpp...
    -I'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include'...
    -L'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64'...
    -l'OpenCL'
